export const CREATE_POST = 'POST/CREATE_POST';
export const FETCH_POSTS = 'POST/FETCH_POSTS';
export const REQUEST_POSTS = 'POST/REQUEST_POSTS';
export const SHOW_LOADER = 'POST/SHOW_LOADER';
export const HIDE_LOADER = 'POST/HIDE_LOADER';
export const REQUEST_POSTS_WITH_ERROR = 'POST/REQUEST_POSTS_WITH_ERROR';

export const ADD_ALERT = 'APP/ADD_ALERT';
export const DELETE_ALERT = 'APP/DELETE_ALERT';
